---
- name: run jhub container in podman 
  hosts: localhost
  connection: local
  become: true

  vars:

    local_user: rocky
    local_user_uid: 1000
    systemd_dir: "/home/{{ local_user }}/.config/systemd/user"
    container_name: jupyter
    image: docker.io/jupyter/base-notebook
    host_port: 8888
    container_port: 8888
    workdir: "/home/{{ local_user }}/jupyter-work"

  tasks:
    - name: Ensure Podman is installed
      ansible.builtin.package:
        name: 
        - podman
        - systemd-container
        state: present

    - name: Create Jupyter work directory
      become_user: "{{ local_user }}"
      ansible.builtin.file:
        path: "{{ workdir }}"
        state: directory
        mode: "0755"

    - name: Create user systemd directory
      become_user: "{{ local_user }}"
      ansible.builtin.file:
        path: "{{ systemd_dir }}"
        state: directory
        mode: "0755"

    - name: Create systemd file
      become_user: "{{ local_user }}"
      ansible.builtin.copy:
        dest: "{{ systemd_dir }}/{{ container_name }}.service"
        mode: "0644"
        content: |
          [Unit]
          Description=Jupyter service (container)

          [Service]
          Type=simple
          ExecStart=/usr/bin/podman run --rm --name {{ container_name }} -p 8888:8888 --volume /home/rocky/jupyter-work:/home/jovyan/work docker.io/jupyter/base-notebook
          Restart=always
          RestartSec=10
         
          [Install]
          WantedBy=default.target

    - name: Reload systemd user units
      become_user: "{{ local_user }}"
      ansible.builtin.command: systemctl --user daemon-reload
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ local_user_uid }}"

    - name: Enable container
      become_user: "{{ local_user }}"
      ansible.builtin.command: systemctl --user enable jupyter.service
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ local_user_uid }}"

    - name: Start container
      become_user: "{{ local_user }}"
      ansible.builtin.command: systemctl --user start jupyter.service
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ local_user_uid }}"

